version: '3.7'

services:
  app-frontend:
    image: node:21.7.3
    command: npx nx dev app
    container_name: app-frontend
    ports:
      - 3000:3000
    environment:
      HOST_NAME: app.adesso.localhost
      API_TOKEN: 566f77f630e358ed9d14dfe2b0eb3d7e2b3ba7881e0e017fd256fba338895ce7
      JWT_SECRET: ADESSO_JWT_SECRET_APP
    working_dir: /ws
    volumes:
      - ./:/ws

  backoffice-frontend:
    image: node:21.7.3
    command: npx nx dev backoffice
    container_name: backoffice-frontend
    ports:
      - 3001:3000
    environment:
      HOST_NAME: backoffice.adesso.localhost
      API_TOKEN: 566f77f630e358ed9d14dfe2b0eb3d7e2b3ba7881e0e017fd256fba338895ce7
      JWT_SECRET: ADESSO_JWT_SECRET_BACKOFFICE
    working_dir: /ws
    volumes:
      - ./:/ws

  npm:
    image: node:21.7.3
    command: npm ci
    container_name: npm
    working_dir: /ws
    volumes:
      - ./:/ws
